[package]
name = "word-rings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"
crossterm = "0.25.0"
ctrlc = "3.2.3"
